Update readme with correct permission
When I followed the instructions as-is, I get the following error

```
kamal@kmahyuddin-mbp sign-up % brew reinstall k8sconfig
==> Fetching envoy/tools/k8sconfig
Error: Your HOMEBREW_GITHUB_API_TOKEN credentials do not have sufficient scope!
Scopes required: repo
Scopes present:  readpackages
```